Repository mozilla/fxa-auth-server, pull requests merged in 2018-09, with the labels that each got.

#2607 fix(recovery): update to support hashing recoveryKeyId
  lib/db.js
  lib/routes/recovery-key.js
  npm-shrinkwrap.json
  test/local/routes/recovery-keys.js
  test/mocks.js
Labels: shipit, train-120, waffle:review

#2612 fix(push): support port numbers in push urls
  CHANGELOG.md
  config/index.js
  npm-shrinkwrap.json
  package.json
  test/local/geodb.js
  test/local/server.js
  test/remote/device_tests.js
Labels: waffle:active

#2610 Release v1.120.0
  CHANGELOG.md
  config/index.js
  npm-shrinkwrap.json
  package.json
  test/local/geodb.js
  test/local/server.js
  test/remote/device_tests.js
Labels: waffle:active

#2613 fix(deps): Pin auth-db-mysql dependency for train-119
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2616 fix(validation): allow https pushCallback URLs that contain :443
  docs/api.md
  lib/devices.js
  lib/routes/validators.js
  test/remote/device_tests.js
  test/remote/token_code_tests.js
  test/remote/totp_tests.js
Labels: waffle:active

#2622 Uplift train 120 into master
  CHANGELOG.md
  docs/api.md
  lib/devices.js
  lib/routes/validators.js
  npm-shrinkwrap.json
  package.json
  test/remote/device_tests.js
Labels: waffle:active

#2623 fix(tests): split running remote and local tests
  npm-shrinkwrap.json
  package.json
  scripts/mocha-coverage.js
  scripts/test-local.sh
  test/remote/db_tests.js
Labels: waffle:review

#2630 fix(keys): return proper error when failing to create duplicate recovery key
  docs/api.md
  lib/db.js
  lib/error.js
  test/remote/recovery_key_tests.js
Labels: train-121, waffle:review

#2634 Release v1.121.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2635 fix(codes): increase token code font size in email
  lib/senders/partials/verify_login_code.html
  lib/senders/templates/_versions.json
  lib/senders/templates/verify_login_code.html
  scripts/write-emails-to-disk.js
Labels: waffle:active

#2637 fix(npm): use npm ci for npm install
  .travis.yml
  Dockerfile-build
  Dockerfile-test
Labels: waffle:active

#2641 feat(scripts): force registry links in shrinkwrap to use tls
  npm-shrinkwrap.json
  package.json
  scripts/tls-shrink.sh
Labels: waffle:review

#2645 fix(tests): fetch cities db from S3
  .travis.yml
Labels: waffle:active

#2638 fix(profile): add profileChangedAt to cert sign and profile
  docs/api.md
  lib/routes/account.js
  lib/routes/sign.js
  lib/signer.js
  lib/tokens/session_token.js
  npm-shrinkwrap.json
  test/remote/account_profile_tests.js
  test/remote/certificate_sign_tests.js
  test/remote/db_tests.js
Labels: train-122, waffle:review

#2644 fix(scripts): make tls-shrink script portable
  scripts/tls-shrink.sh
Labels: waffle:review

#2642 fix(metrics): stash metrics context during the account reset flow
  lib/metrics/context.js
  lib/routes/password.js
  lib/server.js
  test/local/metrics/context.js
  test/local/routes/password.js
  test/mocks.js
Labels: shipit, train-122, waffle:review
