Repository mozilla/fxa-auth-server, pull requests merged in 2018-06, with the labels that each got.

#2460 fix(devices): Remove the unused "device capabilities" API.
  lib/db.js
  lib/devices.js
  lib/routes/devices-and-sessions.js
  package.json
  test/e2e/push_tests.js
  test/local/db.js
  test/local/push.js
  test/local/routes/devices-and-sessions.js
  test/remote/db_tests.js
  test/remote/device_tests.js
  test/remote/push_db_tests.js
Labels: train-114, waffle:active

#2470 fix(docker): base image node:8-alpine and upgrade to npm6
  Dockerfile-build
Labels: waffle:active

#2472 chore(merge): Reverse merge v1.113.5-private into origin/master
  CHANGELOG.md
  docs/api.md
  lib/routes/session.js
  lib/routes/sign.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/sign.js
  test/remote/account_signin_verification_tests.js
  test/remote/totp_tests.js
Labels: waffle:active

#2473 Release v1.114.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2474 fix(l10n): Enable nb-NO locale by updating fxa-shared
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2475 chore(release): Reverse merge train-114 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2478 fix(devices): Do not echo 'capabilities' field in device registration response.
  lib/routes/devices-and-sessions.js
  test/remote/device_tests.js
Labels: waffle:active

#2479 chore(release): Reverse merge train-114 into master
  CHANGELOG.md
  lib/routes/devices-and-sessions.js
  npm-shrinkwrap.json
  package.json
  test/remote/device_tests.js
Labels: waffle:active

#2484 Merge v1.114.3 point-release to master.
  CHANGELOG.md
  lib/routes/recovery-codes.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/recovery-codes.js
  test/mocks.js
Labels: waffle:active

#2485 chore(docs): Expand docs for recovery key usage.
  docs/api.md
  docs/recovery_keys.md
Labels: waffle:active

#2463 feat(recovery): account recovery apis
  docs/api.md
  docs/recovery_keys.md
  lib/db.js
  lib/routes/account.js
  lib/routes/index.js
  lib/routes/password.js
  lib/routes/recovery-keys.js
  lib/routes/session.js
  lib/routes/validators.js
  npm-shrinkwrap.json
  test/client/api.js
  test/client/index.js
  test/local/routes/account.js
  test/local/routes/recovery-keys.js
  test/mocks.js
  test/remote/recovery_key_tests.js
Labels: train-115, waffle:review

#2449 Add support for "device commands" feature.
  config/index.js
  docs/api.md
  docs/device_registration.md
  docs/pushpayloads.schema.json
  lib/db.js
  lib/devices.js
  lib/error.js
  lib/push.js
  lib/pushbox.js
  lib/routes/devices-and-sessions.js
  lib/routes/index.js
  lib/routes/validators.js
  npm-shrinkwrap.json
  package.json
  test/local/db.js
  test/local/push.js
  test/local/pushbox.js
  test/local/routes/devices-and-sessions.js
  test/mocks.js
  test/remote/db_tests.js
  test/remote/device_tests.js
  test/remote/push_db_tests.js
  test/remote/session_tests.js
Labels: shipit, train-115, waffle:review

#2487 Release v1.115.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2492 fix(devices): Fix race between real and placeholder device registration.
  lib/routes/sign.js
  test/local/routes/sign.js
  test/mocks.js
Labels: waffle:active

#2493 Merge v1.115.1 point-release to master.
  CHANGELOG.md
  lib/routes/sign.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/sign.js
  test/mocks.js
Labels: waffle:active
