Repository mozilla/fxa-auth-server, pull requests merged in 2018-08, with the labels that each got.

#2555 fix(sentry): server.events.on takes channels, not channel
  lib/server.js
Labels: waffle:active

#2557 fix(tests): add a check from sentry setup
  lib/server.js
  test/local/sentry.js
Labels: waffle:active

#2529 feat(ci): update to circle 2
  .circleci/config.yml
  circle.yml
Labels: train-118, waffle:active

#2553 feat(recovery): add account recovery email templates
  config/index.js
  lib/metrics/amplitude.js
  lib/routes/account.js
  lib/routes/index.js
  lib/routes/password.js
  lib/routes/recovery-key.js
  lib/senders/email.js
  lib/senders/index.js
  lib/senders/partials/password_reset_account_recovery.html
  lib/senders/partials/post_add_account_recovery.html
  lib/senders/partials/post_remove_account_recovery.html
  lib/senders/templates/_versions.json
  lib/senders/templates/index.js
  lib/senders/templates/password_reset_account_recovery.html
  lib/senders/templates/password_reset_account_recovery.txt
  lib/senders/templates/post_add_account_recovery.html
  lib/senders/templates/post_add_account_recovery.txt
  lib/senders/templates/post_remove_account_recovery.html
  lib/senders/templates/post_remove_account_recovery.txt
  npm-shrinkwrap.json
  test/client/api.js
  test/local/routes/account.js
  test/local/routes/recovery-keys.js
  test/local/senders/email.js
  test/local/senders/templates.js
  test/mocks.js
  test/remote/recovery_key_tests.js
Labels: train-118, waffle:review

#2558 fix(sentry): server.events.on takes channels, not channel
  lib/server.js
Labels: waffle:active

#2559 Release v1.117.2 uplift
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2562 fix(sessionTokens): actually prune expired session tokens
  lib/server.js
  test/mocks.js
Labels: waffle:active

#2535 feat(email): read live email-sending config from redis
  .eslintrc
  config/dev.json
  config/index.js
  lib/db.js
  lib/redis/pool.js
  lib/senders/email.js
  lib/senders/email_service.js
  npm-shrinkwrap.json
  package.json
  test/local/db.js
  test/local/redis/pool.js
  test/local/senders/email.js
  test/local/senders/index.js
  test/remote/account_locale_tests.js
  test/remote/account_signin_verification_tests.js
  test/remote/certificate_sign_tests.js
  test/remote/db_tests.js
  test/remote/redis_tests.js
Labels: waffle:review

#2566 fix(email): ensure email-service errors fail the call to sendMail
  lib/senders/email.js
  lib/senders/email_service.js
  test/local/senders/email_service.js
Labels: train-118, waffle:review

#2564 feat(codes): expose verificationMethod as optional
  lib/routes/account.js
  npm-shrinkwrap.json
  test/remote/account_login_tests.js
  test/remote/token_code_tests.js
Labels: waffle:review

#2570 Release v1.118.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2571 fix(email): JSON.parse live email config after reading from redis
  lib/senders/email.js
  test/local/senders/email.js
Labels: train-119, waffle:review

#2567 Activate pushbox in dev environments
  config/dev.json
Labels: train-120, waffle:review

#2573 fix(server): do not return customs.flag in the destroy route
  lib/routes/account.js
Labels: waffle:active

#2574 feat(email): write live email-sending config to redis
  .travis.yml
  README.md
  package.json
  scripts/email-config.js
  test/local/senders/email.js
  test/scripts/email-config.js
Labels: train-119, waffle:review

#2576 Small improvements for the email-config script
  scripts/email-config.js
  test/scripts/email-config.js
Labels: train-119, waffle:review

#2578 Fixes for email address validation
  lib/routes/validators.js
  test/local/routes/validators.js
Labels: train-119, waffle:review

#2584 fix(scripts): fix the broken api docs generator script
  docs/api.md
  scripts/write-api-docs.js
Labels: waffle:review

#2585 fix(devices): check token.deviceAvailableCommands before dereferencing
  lib/devices.js
  lib/routes/devices-and-sessions.js
  test/local/devices.js
  test/local/routes/devices-and-sessions.js
  test/mocks.js
Labels: train-119, waffle:review

#2586 Merge train-119 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
  test/remote/db_tests.js
  test/remote/device_tests.js
Labels: waffle:active

#2589 Uplift train-119 into master
  CHANGELOG.md
  lib/routes/account.js
  npm-shrinkwrap.json
  package.json
  scripts/delete-account.js
Labels: waffle:active

#2590 fix(tests): update to mocha 5
  npm-shrinkwrap.json
  package.json
  scripts/test-local.sh
Labels: waffle:review

#2597 fix(mysql): fix pushbox mysql
  npm-shrinkwrap.json
Labels: waffle:active

#2598 Release v1.119.3
  CHANGELOG.md
  lib/routes/devices-and-sessions.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/devices-and-sessions.js
  test/remote/db_tests.js
  test/remote/device_tests.js
Labels: waffle:review

#2595 fix(mail_helper): remove '<' from to headers in email service requests
  test/mail_helper.js
Labels: waffle:review

#2600 fix(errors): Surface a backendServiceFailure when connection to db fails.
  lib/error.js
  test/local/error.js
Labels: waffle:active

#2603 chore(email): force value to boolean in account deletion check
  lib/email/bounces.js
Labels: waffle:review

#2604 fix(config): update correct recoveryCodes config
  config/index.js
  lib/routes/totp.js
  test/remote/recovery_code_tests.js
Labels: train-120, waffle:active

#2601 fix(test): update to latest token requirements
  bin/key_server.js
  config/index.js
  docs/api.md
  lib/crypto/base32.js
  lib/crypto/random.js
  lib/routes/account.js
  lib/routes/token-codes.js
  test/local/crypto/base32.js
  test/local/crypto/random.js
  test/remote/db_tests.js
  test/remote/token_code_tests.js
Labels: waffle:active

#2606 fix(logging): log errors when reading/parsing live email config
  lib/senders/email.js
  test/local/senders/email.js
Labels: train-120, waffle:review
