Repository mozilla/fxa-auth-server, pull requests merged in 2018-03, with the labels that each got.

#2324 fix(tests): Make email-polling-expiry tests pass in March.
  test/local/routes/emails.js
Labels: waffle:review

#2305 feat(emails): delete bounced registrations
  lib/email/bounces.js
  test/local/email/bounce.js
Labels: train-107, waffle:active

#2335 chore(uplift): uplift token validation fixes
  docs/api.md
  lib/routes/index.js
  lib/routes/token-codes.js
  test/local/routes/token-codes.js
  test/remote/token_code_tests.js
Labels: waffle:active

#2338 Fixes issue #2333 Migrate to 'Buffer.from'
  lib/crypto/hkdf.js
  lib/routes/idp.js
  test/client/index.js
  test/local/crypto/butil.js
  test/local/crypto/pbkdf2.js
  test/local/crypto/scrypt.js
  test/local/password.js
  test/local/routes/emails.js
  test/local/routes/password.js
  test/local/tokens/forgot_password_token.js
  test/local/tokens/key_fetch_token.js
  test/local/tokens/session_token.js
  test/mailer_helper.js
  test/oauth_helper.js
  test/remote/account_destroy_tests.js
  test/remote/account_locale_tests.js
  test/remote/db_tests.js
  test/remote/misc_tests.js
  test/remote/password_change_tests.js
  test/remote/push_db_tests.js
Labels: waffle:active

#2339 fix(codes): Take token-code uid from the token, not the request payload.
  lib/routes/token-codes.js
  test/client/api.js
  test/client/index.js
  test/local/routes/token-codes.js
  test/remote/token_code_tests.js
Labels: waffle:active

#2341 fix(emails): add location to `verify primary email`
  docs/api.md
  lib/routes/emails.js
  lib/senders/partials/verify_primary.html
  lib/senders/templates/_versions.json
  lib/senders/templates/verify_primary.html
  lib/senders/templates/verify_primary.txt
  test/local/routes/emails.js
  test/remote/recovery_email_resend_code_tests.js
Labels: train-108, waffle:active

#2342 fix(metrics): ensure service is set when possible on amplitude events
  lib/metrics/amplitude.js
  lib/metrics/context.js
  test/local/metrics/amplitude.js
  test/local/metrics/context.js
Labels: waffle:active

#2340 fix(totp): Restrict allowed chars in TOTP code input.
  lib/routes/totp.js
  lib/routes/validators.js
  test/local/routes/totp.js
  test/remote/totp_tests.js
Labels: waffle:active

#2347 fix(deprecation): #2343 Check for deprecated APIs
  lib/crypto/butil.js
  lib/routes/validators.js
  npm-shrinkwrap.json
  package.json
  test/local/crypto/butil.js
  test/local/senders/email.js
  test/mocks.js
Labels: waffle:active

#2353 feat(node): update to node v6.13.1
  Dockerfile-build
Labels: waffle:active

#2346 feat(amr): Report AMR and AAL in relier-facing APIs.
  docs/api.md
  lib/authMethods.js
  lib/routes/account.js
  lib/routes/sign.js
  lib/signer.js
  lib/tokens/session_token.js
  test/client/index.js
  test/local/authMethods.js
  test/local/tokens/session_token.js
  test/remote/account_profile_tests.js
  test/remote/certificate_sign_tests.js
Labels: train-108, waffle:active

#2350 feat(devices): Devices capabilities
  docs/api.md
  docs/endpoint_data.md
  lib/db.js
  lib/devices.js
  lib/routes/devices-and-sessions.js
  npm-shrinkwrap.json
  test/e2e/push_tests.js
  test/local/db.js
  test/local/push.js
  test/local/routes/devices-and-sessions.js
  test/remote/db_tests.js
  test/remote/device_tests.js
  test/remote/push_db_tests.js
Labels: train-108, waffle:review

#2358 chore(deps): upgrade joi to 12.0.0
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2349 feat(totp): initial recovery codes
  config/index.js
  docs/api.md
  lib/customs.js
  lib/db.js
  lib/error.js
  lib/metrics/amplitude.js
  lib/routes/index.js
  lib/routes/recovery-codes.js
  lib/routes/totp.js
  lib/senders/email.js
  lib/senders/index.js
  lib/senders/partials/post_consume_recovery_code.html
  lib/senders/partials/post_new_recovery_codes.html
  lib/senders/templates/_versions.json
  lib/senders/templates/index.js
  lib/senders/templates/post_consume_recovery_code.html
  lib/senders/templates/post_consume_recovery_code.txt
  lib/senders/templates/post_new_recovery_codes.html
  lib/senders/templates/post_new_recovery_codes.txt
  test/client/api.js
  test/client/index.js
  test/local/senders/email.js
  test/local/senders/templates.js
  test/mocks.js
  test/remote/recovery_code_tests.js
  test/remote/totp_tests.js
Labels: train-109, waffle:review

#2356 fix(metrics): include full version information in event data
  lib/devices.js
  lib/userAgent/index.js
  test/local/devices.js
  test/local/server.js
  test/local/user_agent.js
Labels: waffle:active

#2359 fix(server): validate ip addresses before setting them on request object
  lib/routes/validators.js
  lib/server.js
  test/local/server.js
Labels: waffle:review

#2364 fix(totp): throw unverified session in promise chain
  docs/api.md
  lib/routes/totp.js
  test/remote/totp_tests.js
Labels: train-109, waffle:review

#2365 fix(totp): require totp verified session to delete totp token
  lib/routes/emails.js
  lib/routes/totp.js
  npm-shrinkwrap.json
  test/local/routes/totp.js
  test/remote/totp_tests.js
Labels: WIP, waffle:active

#2367 fix(metrics): pass metricsContext to consumeRecoveryCode
  docs/api.md
  lib/routes/recovery-codes.js
  test/client/api.js
  test/remote/recovery_code_tests.js
Labels: waffle:review

#2363 fix(sessions): only return major rev for browser version
  lib/routes/devices-and-sessions.js
  test/local/routes/devices-and-sessions.js
Labels: waffle:active

#2368 chore(db): prevent the possibility of future url-injection bugs
  lib/customs.js
  lib/db.js
  lib/pool.js
  lib/safe-url.js
  npm-shrinkwrap.json
  package.json
  test/local/db.js
  test/local/pool.js
  test/local/safe-url.js
Labels: waffle:review

#2370 fix(validation): Reject URLs with unexpected characters.
  lib/devices.js
  lib/routes/account.js
  lib/routes/session.js
  lib/routes/validators.js
  test/local/routes/session.js
  test/local/routes/validators.js
  test/remote/device_tests.js
Labels: waffle:review

#2372 feat(metrics): add user properties for active device counts
  lib/metrics/amplitude.js
  test/local/metrics/amplitude.js
  test/local/metrics/events.js
Labels: waffle:active

#2369 goaws : test fake sqs/sns server
  config/dev.json
  config/index.js
  lib/notifier.js
Labels: waffle:active

#2374 fix(node): Use Node.js v6.14.0
  Dockerfile-build
  docs/api.md
Labels: waffle:active
