Repository mozilla/fxa-auth-server, pull requests merged in 2018-05, with the labels that each got.

#2420 fix(metrics): remove old flow signature fallback code
  lib/metrics/context.js
  test/local/metrics/context.js
Labels: waffle:review

#2424 fix(newrelic): update newrelic module
  .nsprc
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2430 fix(nsp): update nsp for constantinople
  .nsprc
Labels: waffle:active

#2431 fix(deps): update deps
  .nsprc
  npm-shrinkwrap.json
  package.json
Labels: train-112, waffle:review

#2429 feat(emails): notify users when they are running low on recovery codes
  config/index.js
  lib/routes/recovery-codes.js
  lib/senders/email.js
  lib/senders/index.js
  lib/senders/partials/low_recovery_codes.html
  lib/senders/templates/_versions.json
  lib/senders/templates/index.js
  lib/senders/templates/low_recovery_codes.html
  lib/senders/templates/low_recovery_codes.txt
  npm-shrinkwrap.json
  package.json
  test/local/senders/email.js
  test/local/senders/templates.js
  test/mailbox.js
  test/remote/recovery_code_tests.js
  test/remote/recovery_email_resend_code_tests.js
Labels: train-112, waffle:review

#2432 chore(logging): downgrade location translation error to warning
  lib/routes/devices-and-sessions.js
Labels: waffle:review

#2435 fix(metrics): don't emit route flow events for 404s
  lib/metrics/events.js
  test/local/metrics/events.js
Labels: waffle:review

#2436 fix(logging): log successful sms budget checks
  config/index.js
  lib/senders/sms.js
  test/local/mailer_locales.js
  test/local/senders/index.js
  test/local/senders/sms.js
Labels: waffle:review

#2437 fix(password): require totp verified session to change password
  docs/api.md
  lib/routes/password.js
  test/remote/password_change_tests.js
Labels: shipit, train-112, waffle:review

#2440 fix(docs): fix devices validation output of the doc generator
  docs/api.md
  scripts/write-api-docs.js
Labels: waffle:active

#2443 fix(nsp): fix nsp warnings
  .nsprc
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2442 refactor(metrics): move amplitude email types back here from fxa-shared
  lib/metrics/amplitude.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2444 Land preparatory refactorings for "messages" system.
  lib/devices.js
  lib/pool.js
  lib/push.js
  lib/routes/devices-and-sessions.js
  lib/routes/emails.js
  lib/safe-url.js
  test/e2e/push_tests.js
  test/local/devices.js
  test/local/pool.js
  test/local/push.js
  test/local/routes/devices-and-sessions.js
  test/local/routes/emails.js
  test/local/safe-url.js
  test/mocks.js
  test/remote/push_db_tests.js
Labels: waffle:active

#2446 fix(deps): Update fxa-geodb version, remove nexmo
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2456 fix(params): remove query param for verificationMethod
  lib/routes/account.js
  lib/routes/session.js
  test/local/routes/session.js
Labels: train-113, waffle:review

#2461 fix(deps): Really use v1.113.1 of auth-db-mysql
  npm-shrinkwrap.json
  package.json
Labels: waffle:active
