Repository mozilla/fxa-auth-server, pull requests merged in 2018-12, with the labels that each got.

#2767 fix(oauth): remove prod requirement flag
  fxa-oauth-server/lib/config.js
  fxa-oauth-server/lib/server/index.js
  fxa-oauth-server/test/api.js
Labels: waffle:active

#2766 fix(email): add manage account button in new device login email template
  lib/senders/email.js
  lib/senders/partials/new_device_login.html
  lib/senders/templates/_versions.json
  lib/senders/templates/new_device_login.html
  lib/senders/templates/new_device_login.txt
  test/local/senders/email.js
Labels: waffle:review

#2768 fix(emails): fix arabic emails, add translator tests
  lib/senders/translator.js
  test/local/senders/email.js
Labels: waffle:active

#2770 Release v1.127.0
  CHANGELOG.md
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2773 refactor(oauth ): remove unused grunt tasks from oauth-server
  fxa-oauth-server/Gruntfile.js
  fxa-oauth-server/LICENSE
  fxa-oauth-server/grunttasks/bump.js
  fxa-oauth-server/grunttasks/changelog.js
  fxa-oauth-server/grunttasks/copyright.js
  fxa-oauth-server/grunttasks/eslint.js
  fxa-oauth-server/grunttasks/lint.js
  fxa-oauth-server/grunttasks/release.js
  fxa-oauth-server/lib/db/index.js
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  fxa-oauth-server/scripts/test-local.sh
  grunttasks/eslint.js
Labels: waffle:review

#2774 fix(email): check for null header values in the email service file
  lib/senders/email_service.js
  test/local/senders/email_service.js
Labels: waffle:active

#2775 refactor(oauth): combine oauth deps and package.json with auth
  .circleci/config.yml
  .dockerignore
  .travis.yml
  Dockerfile-oauth-build
  Dockerfile-oauth-test
  fxa-oauth-server/.dockerignore
  fxa-oauth-server/Dockerfile-test
  fxa-oauth-server/lib/routes/root.js
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  fxa-oauth-server/scripts/gen_keys.js
  fxa-oauth-server/scripts/test-local.sh
  fxa-oauth-server/test/server.js
  npm-shrinkwrap.json
  package.json
  scripts/start-local-mysql.sh
  scripts/start-local.sh
Labels: waffle:active

#2776 fix(docker): gen_keys in the OAuth docker container
  Dockerfile-oauth-build
Labels: waffle:active

#2778 chore(release): Merge train-126 into train-127, bump patch number.
  CHANGELOG.md
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  lib/routes/account.js
  lib/routes/recovery-codes.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/account.js
  test/local/routes/recovery-codes.js
  test/mocks.js
  test/remote/totp_tests.js
Labels: waffle:active

#2780 fix(purge): adjust path to package.json
  fxa-oauth-server/bin/purge_expired_tokens.js
Labels: waffle:active

#2781 chore(release): Merge train-127 into master
  CHANGELOG.md
  lib/routes/account.js
  lib/routes/recovery-codes.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/account.js
  test/local/routes/recovery-codes.js
  test/mocks.js
  test/remote/totp_tests.js
Labels: waffle:active

#2742 Formalize our use of oauth-server as a backend microservice
  bin/key_server.js
  config/index.js
  docs/api.md
  fxa-oauth-server/config/test.json
  fxa-oauth-server/lib/assertion.js
  fxa-oauth-server/lib/browserid.js
  fxa-oauth-server/lib/config.js
  fxa-oauth-server/lib/routes/authorization.js
  fxa-oauth-server/lib/routes/key_data.js
  fxa-oauth-server/test/api.js
  fxa-oauth-server/test/assertion.js
  fxa-oauth-server/test/browserid.js
  lib/error.js
  lib/oauthdb.js
  lib/routes/account.js
  lib/routes/index.js
  lib/routes/oauth.js
  lib/routes/validators.js
  lib/senders/email.js
  lib/senders/index.js
  lib/senders/oauth_client_info.js
  lib/server.js
  npm-shrinkwrap.json
  package.json
  scripts/bulk-mailer/index.js
  test/local/config/index.js
  test/local/oauthdb.js
  test/local/routes/oauth.js
  test/local/senders/oauth_client_info.js
  test/local/server.js
  test/mocks.js
Labels: train-128, waffle:review

#2772 refactor(oauth): remove service clients
  fxa-oauth-server/config/test.json
  fxa-oauth-server/docs/api.md
  fxa-oauth-server/docs/service-clients.md
  fxa-oauth-server/lib/config.js
  fxa-oauth-server/lib/db/index.js
  fxa-oauth-server/lib/routes/token.js
  fxa-oauth-server/test/api.js
  fxa-oauth-server/test/routes/token.js
Labels: waffle:active

#2851 feat(metrics): add country and region to activity and flow events
  lib/metrics/events.js
  test/local/devices.js
  test/local/metrics/events.js
  test/local/routes/account.js
  test/local/routes/devices-and-sessions.js
  test/local/routes/emails.js
  test/local/routes/password.js
  test/local/routes/sign.js
  test/local/routes/utils/signin.js
Labels: train-128, waffle:review
