Repository mozilla/fxa-auth-server, pull requests merged in 2018-10, with the labels that each got.

#2636 fix(customs): increase customs timeout to 3000ms
  lib/customs.js
Labels: waffle:active

#2648 chore(sms): log JSON-serialised result if we fail to parse max spend
  lib/senders/sms.js
  test/local/senders/sms.js
Labels: shipit, train-122, waffle:review

#2640 chore(package): bump fxa-shared to 1.0.14 + npm shrinkwrap
  npm-shrinkwrap.json
  package.json
Labels: shipit, train-122, waffle:review

#2650 fix(sms): use a five minute period on polling
  lib/senders/sms.js
  test/local/senders/sms.js
Labels: waffle:active

#2651 fix(deps): Update i18n-abide to remove `npm audit` warnings
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2652 Release v1.122.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2654 Merge train-122 into master
  CHANGELOG.md
  lib/crypto/random.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2655 fix(commands): Assign default TTL to send-tab commands
  lib/routes/devices-and-sessions.js
  test/local/routes/devices-and-sessions.js
Labels: waffle:review

#2656 Uplift train-122 to master
  lib/routes/devices-and-sessions.js
  test/local/routes/devices-and-sessions.js
Labels: merge-me, waffle:active

#2657 Release v1.122.2
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active, you-merge-it

#2658 fix(emails): expose config to prepend domain to verification emails
  config/index.js
  lib/senders/email.js
  test/local/senders/email.js
Labels: train-123, waffle:review

#2659 chore(deps): Update commander, jsxgettext-recursive to remove security warnings.
  grunttasks/l10n-extract.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2663 fix(email): handle the new error structure from fxa-email-service
  lib/senders/email_service.js
  test/local/senders/email_service.js
Labels: train-123, waffle:review

#2664 fix(email): throw error for failed emails during account creation
  docs/api.md
  lib/error.js
  lib/routes/account.js
  lib/routes/utils/signin.js
  test/local/routes/account.js
Labels: waffle:active

#2666 fix(email): include data from headers in email sent events
  lib/senders/email.js
  test/local/senders/email.js
Labels: train-123, waffle:review

#2667 Release v1.123.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2661 fix(mailer): Fix the bulk-mailer, add lots of tests.
  docs/bulk-mail.md
  lib/db.js
  npm-shrinkwrap.json
  package.json
  scripts/bulk-mailer.js
  scripts/bulk-mailer/index.js
  scripts/bulk-mailer/nodemailer-mock.js
  scripts/bulk-mailer/nodemailer-mocks/nodemailer-mock.js
  scripts/bulk-mailer/nodemailer-mocks/stream-output-mock.js
  scripts/bulk-mailer/nodemailer-mocks/write-to-disk-mock.js
  scripts/bulk-mailer/normalize-user-records.js
  scripts/bulk-mailer/read-user-records.js
  scripts/bulk-mailer/send-email-batch.js
  scripts/bulk-mailer/send-email-batches.js
  scripts/dump-users.js
  scripts/dump-users/index.js
  scripts/reset-send-all-batches.sh
  scripts/reset-send-batch.sh
  scripts/reset-send-create-batches.js
  test/scripts/bulk-mailer.js
  test/scripts/bulk-mailer/fixtures/empty-array.json
  test/scripts/bulk-mailer/fixtures/empty.json
  test/scripts/bulk-mailer/fixtures/good-input.json
  test/scripts/bulk-mailer/index.js
  test/scripts/bulk-mailer/nodemailer-mocks/stream-output-mock.js
  test/scripts/bulk-mailer/nodemailer-mocks/write-to-disk-mock.js
  test/scripts/bulk-mailer/normalize-user-records.js
  test/scripts/bulk-mailer/read-user-records.js
  test/scripts/bulk-mailer/send-email-batch.js
  test/scripts/bulk-mailer/send-email-batches.js
  test/scripts/dump-users.js
  test/scripts/fixtures/one_email.txt
  test/scripts/fixtures/one_uid.txt
  test/scripts/fixtures/two_emails.txt
  test/scripts/fixtures/two_uids.txt
Labels: waffle:active

#2670 fix(email): ensure mock senders take precedence over the email service
  lib/senders/email.js
  test/local/senders/email.js
Labels: train-124, waffle:review

#2671 feat(deps): update server dependencies
  docs/api.md
  lib/routes/validators.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2672 fix(ci): remove geodb workaround
  .travis.yml
Labels: waffle:active

#2643 fix(deps): add filtered npm audit
  .nsprc
  .travis.yml
  npm-shrinkwrap.json
  package.json
Labels: train-124, waffle:blocked

#2676 fix(metrics): ensure email events use stashed flow data where applicable
  lib/metrics/context.js
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/password.js
  lib/routes/unblock-codes.js
  lib/routes/utils/signin.js
  lib/server.js
  test/local/metrics/context.js
  test/mocks.js
Labels: shipit, train-123, waffle:review

#2677 fix(metrics): ensure email events use stashed flow data where applicable
  lib/metrics/context.js
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/password.js
  lib/routes/unblock-codes.js
  lib/routes/utils/signin.js
  lib/server.js
  test/local/metrics/context.js
  test/mocks.js
Labels: shipit, train-123, waffle:review

#2678 Merge train-123 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2682 fix(metrics): ensure metrics context is propagated from /account/reset
  lib/routes/account.js
  test/local/routes/account.js
Labels: shipit, train-123, waffle:review

#2686 Merge train 123 into master
  CHANGELOG.md
  lib/routes/account.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/account.js
Labels: waffle:review

#2684 feat(metrics): add code and config for email service notification queue
  bin/email_notifications.js
  config/index.js
  lib/email/notifications.js
  test/local/email/notifications.js
Labels: train-124, waffle:review

#2683 chore(api): remove metrics context data from deprecated endpoints
  .circleci/config.yml
  .travis.yml
  README.md
  docs/api.md
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/password.js
  lib/routes/recovery-codes.js
  lib/routes/totp.js
  package.json
  test/client/api.js
  test/local/routes/account.js
  test/local/routes/password.js
Labels: train-124, waffle:review

#2694 fix(logging): log the reason for account deletions
  lib/routes/account.js
  lib/routes/emails.js
  test/local/routes/account.js
  test/local/routes/emails.js
Labels: train-124, waffle:review

#2698 fix(metrics): use correct format for email service notifications
  lib/email/notifications.js
  test/local/email/notifications.js
Labels: train-124, waffle:review

#2701 fix(tests): remove assertions of profileChangedAt property
  test/remote/db_tests.js
Labels: shipit, train-124, waffle:review

#2702 Merge train-124 into master
  CHANGELOG.md
  fxa-oauth-server/CHANGELOG.md
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  npm-shrinkwrap.json
  package.json
Labels: waffle:review
