Repository mozilla/fxa-auth-server, pull requests merged in 2018-11, with the labels that each got.

#2707 chore(errors): make email-sending errors a 422 for new addresses
  docs/api.md
  lib/error.js
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/utils/signin.js
  test/local/geodb.js
  test/local/routes/account.js
  test/local/routes/emails.js
  test/local/server.js
  test/remote/db_tests.js
Labels: shipit, train-123, waffle:review

#2709 Merge train-123 into train-124
  CHANGELOG.md
  docs/api.md
  lib/error.js
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/utils/signin.js
  test/local/geodb.js
  test/local/routes/account.js
  test/local/routes/emails.js
  test/local/server.js
Labels: shipit, train-124, waffle:review

#2711 fix(errors): reinstate bounce error failures/messaging
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/utils/email.js
  lib/routes/utils/signin.js
  npm-shrinkwrap.json
  package.json
  test/local/routes/account.js
Labels: shipit, train-124, waffle:review

#2710 Merge train-124 into master
  CHANGELOG.md
  docs/api.md
  lib/error.js
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/utils/email.js
  lib/routes/utils/signin.js
  npm-shrinkwrap.json
  package.json
  test/local/geodb.js
  test/local/routes/account.js
  test/local/routes/emails.js
  test/local/server.js
Labels: train-125, waffle:review

#2717 fix(oauth-sentry): arg to server.events.on is "channels" (plural)
  fxa-oauth-server/lib/server/index.js
Labels: blocker, train-124, waffle:active

#2718 Train 124 uplift
  CHANGELOG.md
  fxa-oauth-server/lib/server/index.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2719 fix(test): check that Sentry can be configured if SENTRY_DSN is set
  fxa-oauth-server/lib/server/configureSentry.js
  fxa-oauth-server/lib/server/index.js
  fxa-oauth-server/test/sentry.js
Labels: waffle:active

#2721 fix(release): on `grunt version(:patch?), bump both ./package.json and fxa-oauth-server/package.json
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  grunttasks/bump.js
Labels: waffle:active

#2722 chore(docs): add acr docs
  fxa-oauth-server/docs/api.md
Labels: waffle:active

#2706 chore(clients): Add a client_id for the Reference Browser.
  fxa-oauth-server/config/dev.json
Labels: waffle:active, waffle:review

#2727 fix(config): Add imageUri for reference browser client-id
  fxa-oauth-server/config/dev.json
  test/local/geodb.js
  test/local/server.js
Labels: waffle:active

#2729 chore(tests): make geolocation assertions more robust
  test/known-ip-location.js
  test/local/geodb.js
  test/local/routes/emails.js
  test/local/routes/session.js
  test/local/server.js
  test/mocks.js
Labels: train-125, waffle:review

#2731 chore(oauth): Remove unused `profileChangedAt` parameter in db call.
  fxa-oauth-server/lib/db/mysql/index.js
Labels: waffle:review

#2736 chore(deps): Resolve some `npm audit` warnings in fxa-oauth-server.
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
Labels: waffle:review

#2728 fix(purge): use GET_LOCK("purge_expired_tokens.lock", 3) to only allow one-at-a-time
  fxa-oauth-server/bin/purge_expired_tokens.js
  fxa-oauth-server/lib/db/memory.js
  fxa-oauth-server/lib/db/mysql/index.js
  fxa-oauth-server/test/db/index.js
Labels: train-125, waffle:review

#2734 feat(signin): add ability to skip signin confirmation for specific emails
  config/index.js
  lib/routes/account.js
  test/local/routes/account.js
Labels: train-125, waffle:review

#2739 Train 124 uplift
  CHANGELOG.md
  fxa-oauth-server/lib/routes/client/get.js
  fxa-oauth-server/test/api.js
  npm-shrinkwrap.json
  package.json
  test/known-ip-location.js
  test/local/geodb.js
  test/local/routes/emails.js
  test/local/routes/session.js
  test/local/server.js
  test/mocks.js
Labels: waffle:review

#2741 Release v1.125.0
  CHANGELOG.md
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2749 fix(tests): add Santa Clara to known locations
  test/known-ip-location.js
Labels: waffle:active

#2732 feat(oauth): remove internal oauth server
  fxa-oauth-server/.eslintrc
  fxa-oauth-server/bin/internal.js
  fxa-oauth-server/config/dev.json
  fxa-oauth-server/config/test.json
  fxa-oauth-server/lib/auth_client_management.js
  fxa-oauth-server/lib/config.js
  fxa-oauth-server/lib/routes/client/delete.js
  fxa-oauth-server/lib/routes/client/list.js
  fxa-oauth-server/lib/routes/client/register.js
  fxa-oauth-server/lib/routes/client/update.js
  fxa-oauth-server/lib/routes/developer/activate.js
  fxa-oauth-server/lib/routing.js
  fxa-oauth-server/lib/server/index.js
  fxa-oauth-server/lib/server/internal.js
  fxa-oauth-server/test/api.js
  fxa-oauth-server/test/db/purgeExpiredTokens.js
  fxa-oauth-server/test/lib/server.js
  fxa-oauth-server/test/server.js
Labels: train-126, waffle:review

#2751 feat(deps): update mozlog, newrelic and raven
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2750 feat(deps): update dev deps to match with auth-server
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  fxa-oauth-server/test/api.js
  fxa-oauth-server/test/auth_bearer.js
  fxa-oauth-server/test/browserid.js
  fxa-oauth-server/test/db/helpers.js
  fxa-oauth-server/test/db/index.js
  fxa-oauth-server/test/db/mysql.js
  fxa-oauth-server/test/db/purgeExpiredTokens.js
  fxa-oauth-server/test/events.js
  fxa-oauth-server/test/lib/mocks.js
  fxa-oauth-server/test/lib/util.js
  fxa-oauth-server/test/routes/authorization.js
  fxa-oauth-server/test/routes/token.js
  fxa-oauth-server/test/sentry.js
  fxa-oauth-server/test/server.js
  fxa-oauth-server/test/util.js
Labels: waffle:active

#2754 feat(deps): update sinon to latest
  npm-shrinkwrap.json
  package.json
  test/local/cache.js
  test/local/email/notifications.js
  test/local/email/utils.js
  test/local/features.js
  test/local/log.js
  test/local/metrics/context.js
  test/local/metrics/events.js
  test/local/mock-sns.js
  test/local/notifier.js
  test/local/pool.js
  test/local/push.js
  test/local/routes/account.js
  test/local/routes/devices-and-sessions.js
  test/local/routes/emails.js
  test/local/routes/unblock-codes.js
  test/local/senders/email.js
  test/local/senders/index.js
  test/remote/db_tests.js
Labels: waffle:review

#2756 fix(totp): don't send totp email with invalid code
  lib/routes/totp.js
  test/local/routes/totp.js
  test/mocks.js
Labels: waffle:review

#2758 Release v1.126.0
  CHANGELOG.md
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2760 fix(metrics): emit login complete amplitude event after reset complete
  lib/metrics/amplitude.js
  test/local/metrics/amplitude.js
Labels: shipit, train-126, waffle:review

#2762 Merge train-126 into master
  CHANGELOG.md
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  lib/metrics/amplitude.js
  npm-shrinkwrap.json
  package.json
  test/local/metrics/amplitude.js
Labels: waffle:review

#2763 fix(metrics): ensure email sent amplitude events include device id
  lib/email/utils/helpers.js
  lib/routes/account.js
  lib/routes/password.js
  lib/routes/utils/signin.js
  test/local/email/utils.js
  test/local/routes/account.js
  test/local/routes/password.js
  test/local/routes/utils/signin.js
Labels: shipit, train-126, waffle:review

#2764 Merge train-126 into master
  CHANGELOG.md
  fxa-oauth-server/npm-shrinkwrap.json
  fxa-oauth-server/package.json
  npm-shrinkwrap.json
  package.json
Labels: waffle:review
