Repository mozilla/fxa-auth-server, pull requests merged in 2018-04, with the labels that each got.

#2380 chore(emails): use popular email domain list from fxa-shared
  config/popular-email-domains.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2382 fix(docs): remove old/misleading information about the locale property
  docs/metrics-events.md
Labels: waffle:review

#2381 fix(email): only send new sign-in emails for sync when verifying with totp
  lib/routes/totp.js
  test/client/api.js
  test/remote/totp_tests.js
Labels: train-110, waffle:review

#2388 fix(recovery): set assurance level when verifying with recovery code
  lib/authMethods.js
  lib/tokens/session_token.js
  test/client/index.js
  test/local/authMethods.js
  test/remote/recovery_code_tests.js
Labels: train-110, waffle:review

#2384 refactor(metrics): use boiler-plate amplitude code from fxa-shared
  lib/metrics/amplitude.js
  npm-shrinkwrap.json
  package.json
  test/local/metrics/amplitude.js
  test/local/metrics/events.js
Labels: waffle:review

#2389 fix(devices): Rename pushbox capability to messages in tests
  npm-shrinkwrap.json
  test/e2e/push_tests.js
  test/local/push.js
  test/local/routes/devices-and-sessions.js
  test/remote/db_tests.js
  test/remote/device_tests.js
  test/remote/push_db_tests.js
Labels: waffle:active

#2386 feat(totp): rate limit totp verify actions
  lib/routes/totp.js
  test/local/customs.js
Labels: train-110, waffle:active

#2390 feat(profile): Send "profileDataChanged" event when modifying 2FA status
  lib/routes/totp.js
  test/local/routes/totp.js
Labels: waffle:review

#2391 fix(metrics): stop using user-agent string in flow id check
  lib/metrics/context.js
  test/local/metrics/context.js
  test/mocks.js
Labels: waffle:review

#2393 chore(logging): use a less confusing op on flow event errors
  lib/log.js
  test/local/log.js
Labels: waffle:review

#2396 fix(totp): Change 2FA removed email title to `Two-step authentication disabled`
  lib/senders/email.js
Labels: train-110, waffle:review

#2362 feat(docs): Add documentation for "attached service" notification events
  docs/service_notifications.md
Labels: waffle:review

#2397 fix(recovery): update to latest recovery code requirements
  config/index.js
  docs/api.md
  lib/routes/recovery-codes.js
  lib/routes/totp.js
  npm-shrinkwrap.json
  test/remote/recovery_code_tests.js
  test/remote/totp_tests.js
Labels: train-110, waffle:review

#2398 chore(tests): remove duplicate mocking code
  test/local/ip_profiling.js
Labels: waffle:active

#2400 refactor(email): remove email parameter from config
  config/index.js
  test/local/server.js
Labels: waffle:active

#2392 feat(emails): add email to all manage account email links
  lib/senders/email.js
  test/local/senders/email.js
Labels: train-111, waffle:review

#2407 chore(deps): Update web-push to latest release.
  Dockerfile-test
  npm-shrinkwrap.json
  package.json
  scripts/gen_keys.js
Labels: waffle:active

#2404 feat(node): update to node 8
  .travis.yml
  Dockerfile-build
  package.json
Labels: waffle:active

#2403 chore(config): update redirect domain for dev.json
  config/dev.json
Labels: waffle:review

#2405 fix(totp): check totp before account deletion
  docs/api.md
  lib/routes/account.js
  lib/routes/totp.js
  lib/routes/utils/totp.js
  test/client/api.js
  test/client/index.js
  test/remote/account_destroy_tests.js
Labels: train-111, waffle:review

#2412 feat(notifications): Add SNS msg attributes for service notification filtering
  lib/notifier.js
  test/local/notifier.js
Labels: waffle:active, waffle:review

#2414 fix(scripts): Remove obsolete `bufferize` call from must-reset script.
  scripts/must-reset.js
Labels: waffle:active

#2401 feat(sms): query the available budget in /sms/status
  config/index.js
  lib/routes/sms.js
  lib/senders/sms.js
  test/local/routes/sms.js
  test/local/senders/sms.js
  test/mock-sns.js
Labels: waffle:active
