Repository mozilla/fxa-auth-server, pull requests merged in 2018-07, with the labels that each got.

#2494 feat(email): use fxa-email-server for specific email addresses
  config/index.js
  lib/senders/email.js
  lib/senders/email_service.js
  test/local/senders/email.js
Labels: waffle:active

#2500 feat(server): Update to hapi 17 review
  bin/key_server.js
  lib/routes/emails.js
  lib/routes/password.js
  lib/routes/recovery-codes.js
  lib/routes/signin-codes.js
  lib/routes/totp.js
  lib/server.js
  test/local/routes/emails.js
  test/local/routes/password.js
  test/local/routes/recovery-codes.js
  test/local/routes/recovery-keys.js
  test/local/routes/session.js
  test/local/routes/sms.js
  test/local/routes/token-codes.js
  test/local/routes/totp.js
  test/local/routes/unblock-codes.js
  test/remote/account_create_tests.js
Labels: waffle:active

#2503 Update to hapi 17 review2
  lib/routes/account.js
  lib/routes/defaults.js
  lib/routes/signin-codes.js
  test/local/routes/sign.js
  test/local/routes/signin-codes.js
  test/local/server.js
Labels: waffle:active

#2505 fix(metrics): don't force utm_source=email on links in emails
  config/index.js
  lib/senders/email.js
  test/local/senders/email.js
Labels: shipit, waffle:review

#2510 fix(email): gracefully handle errors from fxa-email-service
  lib/senders/email_service.js
Labels: shipit, train-116, waffle:review

#2508 feat(metrics): add amplitude event properties for email service/sender
  lib/email/utils/helpers.js
  lib/metrics/amplitude.js
  lib/senders/email.js
  npm-shrinkwrap.json
  package.json
  test/local/email/utils.js
  test/local/metrics/amplitude.js
  test/local/senders/email.js
Labels: shipit, train-116, waffle:review

#2483 fix(customs): Fail closed if customs-server gives an error.
  config/index.js
  lib/customs.js
  lib/error.js
  test/local/customs.js
Labels: shipit, train-116, waffle:review

#2513 chore(release): Merge train-116 into master
  CHANGELOG.md
  docs/api.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2486 feat(server): Update to hapi 17
  .eslintrc
  bin/key_server.js
  lib/routes/account.js
  lib/routes/defaults.js
  lib/routes/devices-and-sessions.js
  lib/routes/emails.js
  lib/routes/idp.js
  lib/routes/index.js
  lib/routes/password.js
  lib/routes/recovery-codes.js
  lib/routes/recovery-keys.js
  lib/routes/session.js
  lib/routes/sign.js
  lib/routes/signin-codes.js
  lib/routes/sms.js
  lib/routes/token-codes.js
  lib/routes/totp.js
  lib/routes/unblock-codes.js
  lib/routes/util.js
  lib/server.js
  npm-shrinkwrap.json
  package.json
  test/local/ip_profiling.js
  test/local/routes/account.js
  test/local/routes/devices-and-sessions.js
  test/local/routes/emails.js
  test/local/routes/password.js
  test/local/routes/recovery-codes.js
  test/local/routes/recovery-keys.js
  test/local/routes/session.js
  test/local/routes/sign.js
  test/local/routes/signin-codes.js
  test/local/routes/sms.js
  test/local/routes/token-codes.js
  test/local/routes/totp.js
  test/local/routes/unblock-codes.js
  test/local/server.js
  test/mail_helper.js
  test/oauth_helper.js
  test/remote/account_create_tests.js
  test/remote/hpkp_tests.js
Labels: waffle:review

#2514 fix(push): send FxA commands push messages to iOS devices
  lib/push.js
  test/local/push.js
Labels: waffle:active

#2519 chore(emails): log smtp port in mail_helper.js
  test/mail_helper.js
Labels: waffle:active

#2523 fix(email): fix broken X-SES-CONFIGURATION-SET header
  lib/senders/email.js
  test/local/senders/email.js
Labels: waffle:review

#2524 Merge train-116 into master
  CHANGELOG.md
  lib/senders/email.js
  npm-shrinkwrap.json
  package.json
  test/local/senders/email.js
Labels: waffle:active

#2525 fix(email): make config.sesConfigurationSet default the empty string and assert key is always there
  config/index.js
  test/local/senders/email.js
Labels: waffle:active

#2526 feat(email): add a service property to the X-SES-MESSAGE-TAGS header
  lib/senders/email.js
  test/local/senders/email.js
Labels: waffle:review

#2518 feat(recovery): add recovery key exists and delete recovery key endpoints
  docs/api.md
  docs/recovery_keys.md
  lib/db.js
  lib/error.js
  lib/routes/account.js
  lib/routes/index.js
  lib/routes/recovery-key.js
  lib/routes/recovery-keys.js
  lib/senders/email.js
  npm-shrinkwrap.json
  test/client/api.js
  test/client/index.js
  test/local/routes/account.js
  test/local/routes/recovery-keys.js
  test/mocks.js
  test/remote/recovery_key_tests.js
  test/routes_helpers.js
Labels: waffle:active

#2530 fix(package): fixes for npm security audit
  .nsprc
  .travis.yml
  config/index.js
  grunttasks/nsp.js
  npm-shrinkwrap.json
  package.json
  test/client/api.js
  test/local/server.js
  test/remote/misc_tests.js
Labels: train-117, waffle:review

#2501 feat(scopes): Use shared code lib for checking OAuth scopes.
  lib/routes/account.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2539 chore(browserid): Remove unnecessary browserid routes.
  lib/routes/idp.js
  lib/routes/static/provision.html
  lib/routes/static/sign_in.html
  lib/server.js
  npm-shrinkwrap.json
  package.json
  test/remote/base_path_tests.js
  test/remote/misc_tests.js
  test/remote/sign_key_tests.js
Labels: waffle:review

#2540 Release v1.117.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2543 fix(hapi): use the new server event error handler
  lib/server.js
Labels: waffle:active

#2546 chore(install): Only clone the l10n repo if needed.
  scripts/download_l10n.sh
Labels: waffle:active

#2549 chore(tests): add tests to email_service.js
  test/local/senders/email_service.js
Labels: waffle:active

#2550 fix(redis): recover from invalid token JSON in Redis
  lib/db.js
  test/local/db.js
Labels: waffle:review

#2551 fix(reset): update must-verify script to use string instead of buffer
  scripts/must-reset.js
Labels: waffle:active

#2548 fix(test): increase totp code window
  test/remote/recovery_code_tests.js
  test/remote/totp_tests.js
Labels: waffle:active
