Repository mozilla/fxa-auth-server, pull requests merged in 2018-02, with the labels that each got.

#2298 feat(reset): improve reset for reliers
  lib/senders/email.js
  lib/senders/partials/password_reset.html
  lib/senders/partials/recovery.html
  lib/senders/templates/password_reset.html
  lib/senders/templates/password_reset.txt
  lib/senders/templates/recovery.html
  lib/senders/templates/recovery.txt
Labels: waffle:review

#2303 chore(emails): delete bin/mailer_server.js
  bin/mailer_server.js
  config/index.js
Labels: waffle:active

#2307 chore(logging): downgrade redis.watch.conflict to warning level
  lib/redis/connection.js
  test/local/redis/connection.js
  test/remote/redis_tests.js
Labels: train-106, waffle:review

#2300 feat(totp): TOTP Management APIs
  config/index.js
  docs/api.md
  docs/metrics-events.md
  lib/db.js
  lib/error.js
  lib/routes/account.js
  lib/routes/index.js
  lib/routes/totp.js
  lib/routes/utils/signin.js
  npm-shrinkwrap.json
  package.json
  test/client/api.js
  test/client/index.js
  test/local/routes/totp.js
  test/mocks.js
  test/remote/totp_tests.js
Labels: train-106, waffle:review

#2316 fix(redis): delete clashing tokens from redis in createSessionToken
  config/index.js
  lib/db.js
  test/local/db.js
Labels: waffle:active

#2321 feat(totp): Add verification methods
  lib/db.js
  lib/routes/account.js
  lib/routes/totp.js
  lib/tokens/session_token.js
  npm-shrinkwrap.json
  test/local/tokens/session_token.js
  test/mocks.js
  test/remote/totp_tests.js
Labels: waffle:review
