Repository mozilla/fxa-auth-server, pull requests merged in 2019-04, with the labels that each got.

#3005 fix(devices): return isCurrentDevice for refreshToken device endpoint
  lib/routes/devices-and-sessions.js
  test/remote/device_tests_refresh_tokens.js
Labels: train-134, waffle:review

#2985 Notify push and email on code exchanges
  lib/devices.js
  lib/oauthdb/check-access-token.js
  lib/oauthdb/index.js
  lib/routes/index.js
  lib/routes/oauth.js
  lib/routes/utils/oauth.js
  test/local/oauthdb.js
  test/local/routes/utils/oauth.js
  test/mocks.js
  test/remote/oauth_tests.js
Labels: shipit, train-134, waffle:review

#3007 feat(metrics): amplitude events from the OAuth server for MAU
  fxa-oauth-server/config/dev.json
  fxa-oauth-server/lib/config.js
  fxa-oauth-server/lib/grant.js
  fxa-oauth-server/lib/metrics/amplitude.js
  fxa-oauth-server/lib/routes/verify.js
  fxa-oauth-server/test/grant.js
  fxa-oauth-server/test/metrics/amplitude.js
  fxa-oauth-server/test/routes/verify.js
Labels: shipit, train-134, waffle:review

#3008 fix(config): remove hash alg from config
  fxa-oauth-server/lib/config.js
  fxa-oauth-server/lib/encrypt.js
Labels: waffle:active

#3011 Merge train-134 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: train-134, waffle:review

#3012 chore(docs): Update readme to point to new monorepo
  README.md
Labels: waffle:active
