Repository mozilla/fxa-auth-server, pull requests merged in 2019-03, with the labels that each got.

#2944 Train 131 private uplift
  CHANGELOG.md
  fxa-oauth-server/lib/routes/token.js
  fxa-oauth-server/test/api.js
Labels: waffle:active

#2945 Merge Train 132
  CHANGELOG.md
  fxa-oauth-server/lib/routes/token.js
  fxa-oauth-server/test/api.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2947 refactor(oauthdb): Split OAuthDB implementation across multiple files.
  docs/api.md
  lib/oauthdb.js
  lib/oauthdb/client-info.js
  lib/oauthdb/index.js
  lib/oauthdb/scoped-key-data.js
  lib/oauthdb/utils.js
  lib/routes/oauth.js
  test/local/routes/oauth.js
  test/mocks.js
Labels: train-133, waffle:active

#2949 fix(server): make sure to log errors on server start crash
  bin/key_server.js
Labels: waffle:review

#2951 refactor(redis): use the extracted redis implementation from fxa-shared
  lib/redis.js
  lib/redis/connection.js
  lib/redis/index.js
  lib/redis/pool.js
  npm-shrinkwrap.json
  package.json
  test/local/redis/connection.js
  test/local/redis/index.js
  test/local/redis/pool.js
  test/remote/db_tests.js
  test/remote/redis_tests.js
Labels: train-133, waffle:review

#2967 chore(api): make redis.watch.conflict a 409 instead of 500 error
  docs/api.md
  lib/error.js
  lib/redis.js
  test/local/redis.js
  test/remote/redis_tests.js
Labels: train-133, waffle:review

#2970 fix(docs): add note for ops on how to check raw redis email config
  scripts/email-config.js
Labels: waffle:active

#2946 chore(refactor): Refactor the /token endpoint to improve clarity.
  fxa-oauth-server/lib/db/memory.js
  fxa-oauth-server/lib/routes/token.js
  fxa-oauth-server/test/api.js
Labels: train-133, waffle:review

#2968 feat(basket): Updates to `login` and `verified` events for Basket
  docs/service_notifications.md
  lib/log.js
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/utils/signin.js
  test/local/log.js
  test/local/routes/account.js
  test/local/routes/emails.js
  test/local/routes/utils/signin.js
Labels: waffle:review

#2964 fix(profile_server_messaging): fix db constructor signature
  bin/profile_server_messaging.js
  lib/db.js
  scripts/must-reset.js
Labels: waffle:active

#2977 Merge train-133 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: train-133, waffle:review

#2937 feat(devices): devices API with refreshTokens
  Dockerfile-build
  docs/api.md
  docs/device_registration.md
  fxa-oauth-server/docs/api.md
  fxa-oauth-server/lib/auth_client_management.js
  fxa-oauth-server/lib/routes/destroy.js
  fxa-oauth-server/lib/routes/introspect.js
  fxa-oauth-server/lib/routing.js
  fxa-oauth-server/test/api.js
  lib/db.js
  lib/devices.js
  lib/error.js
  lib/oauthdb/check-refresh-token.js
  lib/oauthdb/index.js
  lib/oauthdb/revoke-refresh-token-by-id.js
  lib/oauthdb/utils.js
  lib/push.js
  lib/routes/devices-and-sessions.js
  lib/routes/index.js
  lib/routes/validators.js
  lib/scheme-refresh-token.js
  lib/server.js
  npm-shrinkwrap.json
  scripts/test-local.sh
  test/client/api.js
  test/client/index.js
  test/lib/util.js
  test/local/db.js
  test/local/devices.js
  test/local/oauthdb/check-refresh-token.js
  test/local/oauthdb/revoke-refresh-token.js
  test/local/push.js
  test/local/routes/devices-and-sessions.js
  test/local/scheme-refresh-token.js
  test/mocks.js
  test/remote/db_tests.js
  test/remote/device_tests.js
  test/remote/device_tests_refresh_tokens.js
  test/remote/push_db_tests.js
  test/test_server.js
Labels: P1, train-133, waffle:active

#2979 Release v1.133.1
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2980 Uplift train-133 to master
  CHANGELOG.md
  Dockerfile-build
  docs/api.md
  docs/device_registration.md
  fxa-oauth-server/docs/api.md
  fxa-oauth-server/lib/auth_client_management.js
  fxa-oauth-server/lib/routes/destroy.js
  fxa-oauth-server/lib/routes/introspect.js
  fxa-oauth-server/lib/routing.js
  fxa-oauth-server/test/api.js
  lib/db.js
  lib/devices.js
  lib/error.js
  lib/oauthdb/check-refresh-token.js
  lib/oauthdb/index.js
  lib/oauthdb/revoke-refresh-token-by-id.js
  lib/oauthdb/utils.js
  lib/push.js
  lib/routes/devices-and-sessions.js
  lib/routes/index.js
  lib/routes/validators.js
  lib/scheme-refresh-token.js
  lib/server.js
  npm-shrinkwrap.json
  package.json
  scripts/test-local.sh
  test/client/api.js
  test/client/index.js
  test/lib/util.js
  test/local/db.js
  test/local/devices.js
  test/local/oauthdb/check-refresh-token.js
  test/local/oauthdb/revoke-refresh-token.js
  test/local/push.js
  test/local/routes/devices-and-sessions.js
  test/local/scheme-refresh-token.js
  test/mocks.js
  test/remote/db_tests.js
  test/remote/device_tests.js
  test/remote/device_tests_refresh_tokens.js
  test/remote/push_db_tests.js
  test/test_server.js
Labels: waffle:active

#2984 fix(deps): fix npm advisory 788
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2987 fix(api): remove redundant query params from /recovery_email/verify_code
  docs/api.md
  lib/routes/emails.js
Labels: train-134, waffle:review

#2988 chore(docs): disable the auto-generated api docs script
  docs/api.md
  grunttasks/doc.js
  package.json
  scripts/write-api-docs.js
Labels: train-134, waffle:review

#2989 refactor(config): cache repetitive calls to conf.get
  config/index.js
Labels: train-134, waffle:review

#2969 feat(oauth): Use an assertion to directly grant tokens at /token.
  fxa-oauth-server/docs/api.md
  fxa-oauth-server/lib/db/memory.js
  fxa-oauth-server/lib/db/mysql/index.js
  fxa-oauth-server/lib/error.js
  fxa-oauth-server/lib/grant.js
  fxa-oauth-server/lib/routes/authorization.js
  fxa-oauth-server/lib/routes/key_data.js
  fxa-oauth-server/lib/routes/token.js
  fxa-oauth-server/test/api.js
  fxa-oauth-server/test/grant.js
  fxa-oauth-server/test/routes/authorization.js
  fxa-oauth-server/test/routes/token.js
Labels: waffle:review

#2932 feat(oauth): Add /oauth/authorization route, authenticated with a sessionToken
  docs/api.md
  lib/error.js
  lib/oauthdb/create-authorization-code.js
  lib/oauthdb/index.js
  lib/oauthdb/utils.js
  lib/routes/oauth.js
  lib/routes/validators.js
  test/client/api.js
  test/client/index.js
  test/local/oauthdb/create-authorization-code.js
  test/local/routes/oauth.js
  test/mocks.js
  test/remote/oauth_tests.js
Labels: waffle:review

#2983 feat(oauth): Add /oauth/token route, optionally authed via sessionToken
  docs/api.md
  fxa-oauth-server/config/dev.json
  lib/error.js
  lib/oauthdb/grant-tokens-from-authorization-code.js
  lib/oauthdb/grant-tokens-from-credentials.js
  lib/oauthdb/grant-tokens-from-refresh-token.js
  lib/oauthdb/index.js
  lib/oauthdb/utils.js
  lib/routes/oauth.js
  lib/routes/validators.js
  test/client/api.js
  test/client/index.js
  test/local/oauthdb/grant-tokens-from-authorization-code.js
  test/local/oauthdb/grant-tokens-from-refresh-token.js
  test/local/oauthdb/grant-tokens-from-session-token.js
  test/local/routes/oauth.js
  test/mocks.js
  test/remote/oauth_tests.js
Labels: waffle:review

#2990 feat(email): reinstate account verification reminder emails
  config/index.js
  docs/api.md
  docs/metrics-events.md
  lib/metrics/amplitude.js
  lib/routes/account.js
  lib/routes/emails.js
  lib/routes/index.js
  lib/senders/email.js
  lib/senders/templates/_versions.json
  lib/senders/templates/index.js
  lib/senders/templates/verification_reminder_first.html
  lib/senders/templates/verification_reminder_first.txt
  lib/senders/templates/verification_reminder_second.html
  lib/senders/templates/verification_reminder_second.txt
  lib/verification-reminders.js
  npm-shrinkwrap.json
  package.json
  scripts/verification-reminders.js
  test/local/devices.js
  test/local/email/bounce.js
  test/local/ip_profiling.js
  test/local/metrics/amplitude.js
  test/local/metrics/events.js
  test/local/routes/account.js
  test/local/routes/emails.js
  test/local/routes/recovery-codes.js
  test/local/routes/token-codes.js
  test/local/routes/utils/signin.js
  test/local/senders/email.js
  test/local/senders/index.js
  test/local/senders/templates.js
  test/local/server.js
  test/local/verification-reminders.js
  test/mocks.js
  test/remote/redis_tests.js
Labels: shipit, train-134, waffle:review
