Repository mozilla/fxa-auth-server, pull requests merged in 2019-02, with the labels that each got.

#2901 feat(l10n): Enable Catalan (ca)
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#2902 fix(tests): pass tests in node 10
  .travis.yml
  lib/crypto/scrypt.js
  npm-shrinkwrap.json
  package.json
Labels: train-130, waffle:review

#2903 fix(scripts): sanely handle refreshTokens in the docs script
  docs/api.md
  scripts/write-api-docs.js
Labels: waffle:review

#2905 Release v1.130.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2909 feat(email): Update verification email for OAuth reliers.
  lib/senders/email.js
  lib/senders/partials/verify.html
  lib/senders/templates/_versions.json
  lib/senders/templates/verify.html
  lib/senders/templates/verify.txt
  test/local/senders/email.js
Labels: waffle:review

#2911 fix(key-data): fix key-data endpoint for fresh accounts
  fxa-oauth-server/lib/routes/key_data.js
  fxa-oauth-server/test/api.js
Labels: waffle:active

#2913 Uplift train-130 to master
  CHANGELOG.md
  fxa-oauth-server/lib/routes/key_data.js
  fxa-oauth-server/test/api.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2920 chore(deps): Update handlebars dependency.
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2918 fix(devices): return full device response on spurious updates
  lib/routes/devices-and-sessions.js
  test/local/routes/devices-and-sessions.js
Labels: waffle:active

#2924 chore(clients): Add a dev client_id for Fenix
  fxa-oauth-server/config/dev.json
Labels: waffle:review

#2925 chore(deploy): upgrade to node 10
  .circleci/config.yml
  .travis.yml
  Dockerfile-build
  Dockerfile-oauth-build
  npm-shrinkwrap.json
Labels: train-132, waffle:review

#2926 Merge train-131 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: train-131, waffle:review

#2910 fix(errors): add some more context to our 500 errors
  docs/api.md
  lib/backendService.js
  lib/error.js
  lib/safe-url.js
  lib/server.js
  test/local/backendService.js
  test/local/error.js
  test/local/safe-url.js
  test/local/server.js
Labels: train-132, waffle:review

#2929 fix(metrics): reinstate entrypoint to the metrics context schema
  docs/api.md
  lib/metrics/context.js
  test/local/log.js
  test/local/metrics/context.js
  test/local/metrics/events.js
  test/local/routes/account.js
  test/mocks.js
  test/remote/account_create_tests.js
Labels: train-132, waffle:review

#2930 Merge train-131 into master
  CHANGELOG.md
  docs/api.md
  lib/metrics/context.js
  npm-shrinkwrap.json
  package.json
  test/local/log.js
  test/local/metrics/context.js
  test/local/metrics/events.js
  test/local/routes/account.js
  test/mocks.js
  test/remote/account_create_tests.js
Labels: train-131, waffle:review

#2934 fix(db): Stop using deprecated 'sessionWithDevice' db route.
  lib/db.js
Labels: waffle:review
