Repository mozilla/fxa-auth-server, pull requests merged in 2019-01, with the labels that each got.

#2852 feat(validation): Have `validators.scope` automatically parse the value to a `ScopeSet`.
  fxa-oauth-server/lib/routes/authorization.js
  fxa-oauth-server/lib/routes/key_data.js
  fxa-oauth-server/lib/routes/token.js
  fxa-oauth-server/lib/validators.js
  fxa-oauth-server/test/api.js
Labels: waffle:review

#2853 chore(docs): Fix typo "depricated" -> "deprecated"
  fxa-oauth-server/docs/api.md
Labels: waffle:active, waffle:review

#2855 chore(grunt): remove grunt bump for oauth-server
  grunttasks/bump.js
Labels: shipit, train-128, waffle:active

#2856 Release v1.128.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2857 fix(circle): can never have enough version.json
  .circleci/config.yml
Labels: waffle:active

#2861 Merge train-128 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: train-128, waffle:review

#2864 chore(package): disable security advisory 766 for sandbox dependency
  .nsprc
Labels: train-129, waffle:review

#2866 Release v1.128.2
  CHANGELOG.md
  lib/senders/oauth_client_info.js
  npm-shrinkwrap.json
  package.json
  test/local/senders/oauth_client_info.js
Labels: waffle:active

#2868 Fix oauth client name validation
  CHANGELOG.md
  lib/oauthdb.js
  lib/routes/index.js
  npm-shrinkwrap.json
  package.json
  test/local/oauthdb.js
Labels: waffle:active

#2869 chore(release): Merge private train-128 into public train-128
  .nsprc
  CHANGELOG.md
  fxa-oauth-server/lib/routes/redirect.js
  fxa-oauth-server/test/api.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2870 chore(deps): Update to fxa-shared@1.0.15
  npm-shrinkwrap.json
  package.json
  test/local/metrics/amplitude.js
Labels: train-129, waffle:review

#2872 fix(oauth): Allow keys_jwk through GET /authorization
  fxa-oauth-server/lib/routes/redirect.js
  fxa-oauth-server/test/api.js
Labels: train-128, waffle:review

#2874 fix(circle): version.json "source" should be code repository
  .circleci/config.yml
Labels: waffle:active

#2863 fix(config): use local redirect for the reference browser
  fxa-oauth-server/config/dev.json
Labels: waffle:active

#2873 Release v1.128.5
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2876 Scoped keys data fixes
  config/index.js
  fxa-oauth-server/config/dev.json
  lib/oauthdb.js
  test/local/oauthdb.js
Labels: waffle:active

#2879 fix(metrics): stop emitting route flow events for status endpoints
  lib/metrics/events.js
  test/local/metrics/events.js
Labels: waffle:review

#2883 fix(email): add missing query params to link in new device email
  lib/senders/email.js
  test/local/senders/email.js
Labels: train-129, waffle:review

#2881 Release v1.129.0
  CHANGELOG.md
  lib/senders/email.js
  npm-shrinkwrap.json
  package.json
  test/local/senders/email.js
  test/local/user_agent.js
Labels: waffle:review

#2889 fix(error): remove `A` from totpTokenNotFound and totpTokenAlreadyExists errors
  docs/api.md
  lib/error.js
Labels: waffle:active

#2886 fix(logs): rename `code` to `status` on request.summary log lines
  lib/log.js
  test/local/log.js
Labels: train-129, waffle:review

#2890 Merge train-129 into master
  CHANGELOG.md
  lib/log.js
  npm-shrinkwrap.json
  package.json
  test/local/log.js
Labels: train-129, waffle:review

#2894 Train 129 into master
  CHANGELOG.md
  docs/api.md
  fxa-oauth-server/lib/routes/redirect.js
  fxa-oauth-server/test/api.js
  lib/routes/oauth.js
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#2897 fix(sms): catch errors thrown from phoneNumberUtil.parse
  lib/routes/sms.js
  test/local/routes/sms.js
Labels: train-130, waffle:review

#2865 feat(metrics): Emit additional data for the DataFlow fraud detection pipeline.
  lib/log.js
  test/local/log.js
Labels: train-130, waffle:review

#2898 fix(metrics): Fix entrypoint being overwritten for every event.
  npm-shrinkwrap.json
  package.json
  test/local/metrics/amplitude.js
Labels: waffle:active
